# Network Fabric vlabs
Host 10.*.0.4
    User cEosAdmin

# Network Cloud simulators via az ssh arc - avoid adding temporary keys to
# agent.
Host simdev-*-vm-1
    AddKeysToAgent no

# B37 jump box also via az ssh arc.
Host b37-westus3-dev-azl3-arc-vm
    AddKeysToAgent no
    ForwardAgent yes
