# [source.crates-io]
# replace-with = 'ms-crates-io'

# [registries.ms-crates-io]
# index = 'sparse+https://pkgs.dev.azure.com/msazuredev/AzureForOperatorsIndustry/_packaging/AzureForOperatorsIndustry_PublicPackages/Cargo/index/'
# credential-provider = "msrustup"

[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
