# [source.crates-io]
# replace-with = "afo-crates-io-mirror"

[registry]
# default = "afo"
global-credential-providers = ["msrustup", "cargo:token"]

[registries.ms-crates-io]
index = 'sparse+https://crates.microsoft.com/crates-io/'

[registries.afo-crates-io-mirror]
index = "sparse+https://pkgs.dev.azure.com/msazuredev/AzureForOperators/_packaging/crates-io-mirror/Cargo/index/"

[registries.afo]
index = "sparse+https://pkgs.dev.azure.com/msazuredev/AzureForOperators/_packaging/rust/Cargo/index/"

[registries.crates-ms]
index = 'sparse+https://crates.microsoft.com/index/'

[registries.metaswitch]
index = "https://git.datcon.co.uk/infrastructure.public/crates-registry.git"

[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
